services:
  vegetable-app:
    build: .
    image: vegetable-order-app 
    container_name:  vegetable-order-app-mongo-1
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/vegetable_order_app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
