apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegetable-deployment
  namespace: siva-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vegetable
  template:
    metadata:
      labels:
        app: vegetable
    spec:
      containers:
        - name: vegetable-container
          image: sivamani07/vegetable-order-app:v1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
              name: vegetable-app-config
