replicas: 2

deployment:
  labels:
    app: vegetable
  name: vegetable-container
  port: 3000

image:
  repository: sivamani07/vegetable-order-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  app: vegetable
  port: 80
  targetPort: 3000
  type: LoadBalancer

config:
  MONGO_URL: "mongodb://vegetable-release-mongo:27017/vegetableDB"
  PORT: "3000"
  SESSION_SECRET: "vegetable-secret"
  MONGO_INITDB_DATABASE: "vegetableDB"

secret:
  SESSION_SECRET: "vegetable-secret"

mongo:
  replicas: 1
  serviceName: vegetable-release-mongo
  labels:
    app: mongo
  image:
    repository: mongo
    tag: "6"
    pullPolicy: IfNotPresent
  port: 27017
  service:
    port: 27017
    targetPort: 27017
    clusterIP: None
  storageClassName: gp2
  storage: 1Gi

pvc:
  name: mongo-pvc
  accessMode: ReadWriteOnce
  storage: 2Gi
  storageClassName: gp2
storageClass:
  name: retail-sc
  provisioner: ebs.csi.aws.com
  type: gp3
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
