apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegetable-deployment
  namespace: siva-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vegetable
  template:
    metadata:
      labels:
        app: vegetable
    spec:
      containers:
        - name: vegetable-container
          image: sivamani07/vegetable-order-app:v1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: vegetable-app-config
                  key: MONGO_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: vegetable-app-config
                  key: PORT
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: vegetable-app-config
                  key: SESSION_SECRET
